### ISSUE TITLE
P2P Room Module

### ISSUE THREAD

**Issue by Ioane5** [Ioane5/ms_thesis#2]
This is the first Part of my thesis Backend Solution. 

### Tasks

- [x] Backend Server Implementation (Socket.io)
- [x] Heroku Deploy
- [x] Client JS implementation
- [x] Corresponding paragraph update in Thesis doc

deadline: 23 feb.
