### ISSUE TITLE
Implement Message Box

### ISSUE THREAD

**Issue by Ioane5** [Ioane5/ms_thesis#3]
This is second part of a Module called _Message Box_

### Tasks

- [x] Implementing Backend Server
- [x] Implementing Client sync (the one that sends, the one that receives)
- [x] Thesis paragraph Update

Deadline: 2 March
