### ISSUE TITLE
Security Enhansements

### ISSUE THREAD

**Issue by Ioane5** [Ioane5/ms_thesis#4]
Security is very important part of the Thesis. 
Since everybody can get message for others. 
### Tasks

- [x] User ID Management
- [x] Message Encryption with private key
- [x] Message readability for shared users only
- [x] Message cannot be modified by adversary.
- [x] Client Verifications for Message and rejecting if needed. 
- [x] Server only gives message to those who can verify themselves. 
- [x] Thesis Update with security Module. 

Deadline: 16 March
